### ISSUE TITLE
EL / Greek VRNs do not validate

### ISSUE THREAD

**Issue by Kier** [drahosistvan/vatvalidation#10]
I've noticed that this tool marks EL-prefixed VRNs as invalid.

The following VRNs are valid according to VIES, but invalid when checked with this validator:

- EL027408226
- EL032880379
- EL800620092

I think the problem is the use of 'GR' in the formatVatNumber $pattern, where 'GR' is used rather than 'EL'.

Fix: `$pattern = '/^(AT|BE|BG|CY|CZ|DE|DK|EE|EL|ES|FI|FR|GB|HR|HU|IE|IT|LT|LU|LV|MT|NL|PL|PT|RO|SE|SI|SK)[A-Z0-9]{6,20}$/';`

**Comment by drahosistvan** [comment]
@Kier #11 was merged into master! Thank you very much for your fast fix.
Maybe in later versions I will refactor the code based on this specification: https://www.avalara.com/vatlive/en/eu-vat-rules/eu-vat-number-registration/eu-vat-number-formats.html
