### ISSUE TITLE
Doesn't validate format for Swiss VAT IDs

### ISSUE THREAD

**Issue by cocowalla** [drahosistvan/vatvalidation#5]
Take the VAT ID for [Swiss](https://www.swiss.com/UK/EN/terms-conditions/imprint.html) as an example: `CHE-105.918.070 MWST`.

Attempts to validate it result in `WrongVatNumberFormatException`. This is the same if you remove spaces, hyphens and dots.

Looking at [the source](https://github.com/drahosistvan/vatvalidation/blob/master/src/VatValidation/VatValidation.php#L51), it does look like Switzerland isn't handles by the regex pattern.

**Comment by cocowalla** [comment]
Gah, Switzerland isn't in the EU... I seriously need more coffee!

**Comment by drahosistvan** [comment]
np ;)
