### ISSUE TITLE
Regex issues

### ISSUE THREAD

**Issue by cocowalla** [drahosistvan/vatvalidation#6]
Some valid VAT numbers end with letters, e.g. [CY99200002N](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=CY&iso=CY&vat=99200002N), [CY99000027S](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=CY&iso=CY&vat=99000027S), [ESN8261290D](http://ec.europa.eu/taxation_customs/vies/vatResponse.html), [IE1113202EH](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=IE&iso=IE&vat=1113202EH), and some contain them in the middle, e.g. [IE8O47531K](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=IE&iso=IE&vat=8O47531K), [IE8E86432H](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=IE&iso=IE&vat=8E86432H), [NL822667800B01](http://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=EN&ms=NL&iso=NL&vat=822667800B01), but the regex pattern currently being used doesn't allow for these. It also doesn't allow Greek VAT numbers.

I think the solution here is to use a less-strict regex pattern, such as:

`"/^(AT|BE|BG|CY|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IE|IT|LT|LU|LV|MT|NL|PL|PT|RO|SE|SI|SK)[A-Z0-9]{6,20}$/"`

**Comment by drahosistvan** [comment]
Dear @cocowalla,

Thank you for your report! It was very useful. Please check version [1.0.1 ](https://github.com/drahosistvan/vatvalidation/releases/tag/1.0.1).

👍👍✌✌👌👌

**Comment by cocowalla** [comment]
Works as expected now, and nice that you added a test too - thanks 👍
