### ISSUE TITLE
Composer keywords

### ISSUE THREAD

**Issue by vvasiloi** [drahosistvan/vatvalidation#8]
https://github.com/drahosistvan/vatvalidation/blob/1c620c6495949cfe53cc7c2f30a7e7b597dca63d/composer.json#L6-L8

I would suggest replacing those keywords with something related to the package, like `vias`, `vat`, `validation`.
That will make it easier to find the package.

**Comment by drahosistvan** [comment]
Thank you for your report. Fixed.
